[workspace]

members = [
    "cli/signal",
    "cli/fledger",
    "flnet-libc",
    "flnet-wasm",
    "web",
    "flmodules",
    "flutils",
    "flnet",
    "flnode"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
