FROM debian:bookworm-slim

RUN apt update && apt install patchelf

COPY target-common/release/fledger fledger
RUN patchelf --set-interpreter /usr/lib64/ld-linux-x86-64.so.2 fledger

FROM debian:bookworm-slim
WORKDIR /fledger
COPY --from=0 fledger /fledger/fledger

ENTRYPOINT ["/fledger/fledger", "-vv"]
