FROM debian:bookworm-slim

RUN apt update && apt install patchelf

COPY target-common/release/flsignal flsignal
RUN patchelf --set-interpreter /usr/lib64/ld-linux-x86-64.so.2 flsignal

FROM debian:bookworm-slim
WORKDIR /fledger
COPY --from=0 flsignal /fledger/flsignal

ENTRYPOINT ["/fledger/flsignal", "-vv"]
