FROM lukemathwalker/cargo-chef as planner
WORKDIR /fledger
COPY . .
RUN cargo chef prepare

FROM lukemathwalker/cargo-chef as cacher
WORKDIR /fledger
COPY --from=planner /fledger/recipe.json recipe.json
RUN cargo chef cook --release

FROM rust as builder
WORKDIR /fledger
COPY . .
COPY --from=cacher /fledger/target target
COPY --from=cacher /usr/local/cargo /usr/local/cargo
RUN cd cli/signal; cargo build --release --bin signal

FROM rust as runtime
WORKDIR /fledger
COPY --from=builder /fledger/cli/signal/target/release/signal signal
ENTRYPOINT ["/fledger/signal"]
