FROM debian:bookworm-slim

RUN apt update && apt install -y patchelf ca-certificates

COPY target-common/release/fledger fledger
RUN patchelf --set-interpreter /usr/lib64/ld-linux-x86-64.so.2 fledger
EXPOSE 0-65535/udp
FROM debian:bookworm-slim
WORKDIR /fledger
COPY --from=0 fledger /fledger/fledger
COPY --from=0 /etc/ssl /etc/ssl

RUN mkdir /fledger/data

ENTRYPOINT ["/fledger/fledger", "-vv"]
