FROM rust as builder
WORKDIR fledger
COPY vendor vendor

COPY dummy.rs common/src/main.rs
COPY common/Cargo.toml common/
RUN cd common; cargo build

COPY dummy.rs cli/signal/src/main.rs
COPY cli/signal/Cargo.toml cli/signal/
RUN cd cli/signal; cargo build --release

COPY . .
#COPY cli/signal/src cli/signal/src
# COPY common/src common/src
# RUN cd common; cargo build
RUN cd cli/signal; cargo build --release

FROM rust as runtime
COPY --from=builder fledger/cli/signal/target/release/signal /usr/local/bin
ENTRYPOINT ["/usr/local/bin/signal"]