[package]
name = "flnet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flutils = {path = "../flutils"}

# The "js" is to make sure it also works for the flnode and web crates
getrandom = { version = "0.2.3", features = ["js"] }
async-trait = "0.1.51"
rand = "0.7.3"
serde = { version = "1.0.127", features = ["derive"] }
serde_derive = "1.0.127"
serde_json = "1.0.66"
toml = "0.5.8"
names = "0.12.0"
thiserror = "1.0.26"
futures = "0.3.16"
log = "0.4.14"
sha2 = "0.10.1"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }

[dependencies.web-sys]
features = [
  "Storage",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "MessageEvent",
  "RtcPeerConnection",
  "RtcSignalingState",
  "RtcSdpType",
  "RtcSessionDescriptionInit",
  "RtcPeerConnectionIceEvent",
  "RtcIceCandidate",
  "RtcIceCandidateInit",
  "RtcIceConnectionState",
  "RtcIceGatheringState",
  "RtcDataChannel",
  "RtcDataChannelEvent",
  "RtcDataChannelState",
  "Navigator",
]
version = "0.3.51"
