run:
	/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
		--headless --disable-gpu --remote-debugging-port=9223 \
		--user-data-dir="./cache" http://localhost:8080

run_old:
	/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
		--headless --disable-gpu --user-data-dir="./cache" \
		localhost:8080

